### ISSUE TITLE
What're the means of the push and pull of SAPNet?

### ISSUE THREAD

**Issue by Ssakura-go** [ShenZheng2000/SAPNet#5]
Hi, dear author,

I'm glad to have the oppotunity to take knowledge of your work and obtain a lot from it. (SAPNet) However, I have a problem with it. I found that push and pull in that model architecture for SAPNet, but I couldn't find what it displays in the code.

If you are free, could you please give me a reply?
Thks~
Best wishes to you!

**Comment by ShenZheng2000** [comment]
Hi, Ssakura! Thanks for your interest in our work. 

The push-and-pull strategy is defined in the perceptual contrastive loss (PCL) [here](https://github.com/ShenZheng2000/SAPNet-for-image-deraining/blob/56dd6e4ebc7da57a9e6ea8b2bb1a278a3da6dbad/loss_fun.py#L51). Basically, PCL pulls `pred` towards `pos`, and pushes `pred` away from `neg`.

**Comment by Ssakura-go** [comment]
> here
Roger that.
Thanks for your quick reply!
